factories:
    example_book_service: Book/Service/Factory/ExampleBookServiceFactory
invokables:
    example_book_service: Book/Service/ExampleBookService
    example_author_service: Author/Service/ExampleAuthorService