factories:
    example_book_main_service: Book/Service/Factory/ExampleBookServiceMainFactory
invokables:
    example_book_main_service: Book/Service/ExampleBookMainService
    example_author_main_service: Author/Service/ExampleAuthorMainService