scripts:
    - Kernel/Config.js
    - Kernel/Router.js
    - Kernel/Utility.js
    - Kernel/ServiceLocator.js
    - Kernel/Translation.js
    - Kernel/Translator.js
    - Kernel/Autoload/MasterAutoload.js
    - Kernel/Dispatcher/DispatcherMaster.js
    - Kernel/Dispatcher/DispatcherBase.js
    - Kernel/Factory/MasterFactory.js
# INITIALIZER
    - Kernel/Initializer/MasterInitializer.js
    - Kernel/Initializer/ModuleInitializer.js
# MANAGER
    - Kernel/Managers/MasterManager.js
    - Kernel/Managers/RouteManager.js
    - Kernel/Managers/ServiceManager.js
    - Kernel/Managers/ModelManager.js
    - Kernel/Managers/TemplateManager.js
    - Kernel/Managers/ControllerManager.js
    - Kernel/Managers/EntityManager.js

    - Kernel/Route/MasterRoute.js
    - Kernel/Service/MasterService.js
    - Kernel/Route/Type/MasterRouteType.js
    - Kernel/Route/Type/LitteralRouteType.js
    - Kernel/Route/Type/TranslationRouteType.js
    - Kernel/Route/Type/ParamsRouteType.js
    - Kernel/Controller/MasterController.js
    - Kernel/Template/MasterTemplate.js
    - Kernel/Template/View/MasterView.js
# MODULE EXAMPLE
    - Modules/Example/ExampleAutoload.js
    - Modules/Example/Bundle/Book/Route/ExampleBookMainRoute.js
    - Modules/Example/Bundle/Book/Service/ExampleBookMainService.js
    - Modules/Example/Bundle/Author/Route/ExampleAuthorMainRoute.js
    - Modules/Example/Bundle/Author/Service/ExampleAuthorMainService.js
    - Modules/Example/Bundle/Book/Service/Factory/ExampleBookServiceMainFactory.js
    - Modules/Example/Bundle/Book/Controller/ExampleBookMainController.js
    - Modules/Example/Bundle/Author/Template/ExampleAuthorMainTemplate.js
    - Modules/Example/Bundle/Author/Template/View/ExampleAuthorTemplateMainView.js
    - Modules/Example/Bundle/Book/Template/ExampleBookMainTemplate.js
    - Modules/Example/Bundle/Book/Template/View/ExampleBookTemplateMainView.js
# MODULE BODY
    - Modules/Body/BodyAutoload.js
    # - Modules/Body/Bundle/Left/Route/BodyLeftMainRoute.js
    # - Modules/Body/Bundle/Left/Service/BodyLeftMainService.js
    # - Modules/Body/Bundle/Right/Route/BodyRightMainRoute.js
    # - Modules/Body/Bundle/Right/Service/BodyRightMainService.js
    # - Modules/Body/Bundle/Left/Service/Factory/BodyLeftServiceMainFactory.js
    # - Modules/Body/Bundle/Left/Controller/BodyLeftMainController.js
    - Modules/Body/Bundle/Right/Template/BodyRightMainTemplate.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateMainView.js
    - Modules/Body/Bundle/Left/Template/BodyLeftMainTemplate.js
    - Modules/Body/Bundle/Left/Template/View/BodyLeftTemplateMainView.js
    - Modules/Body/Bundle/Cover/Template/BodyCoverMainTemplate.js
    - Modules/Body/Bundle/Cover/Template/View/BodyCoverTemplateMainView.js
# START APPLICATION
    - main.js