scripts : 
    - Vendors/React.js
    - Vendors/socket.io.js
    - Kernel/Config.js
    - Kernel/Router.js
    - Kernel/Utility.js
    - Kernel/ServiceLocator.js
    - Kernel/Translation.js
    - Kernel/Translator.js
    - Kernel/Autoload/MasterAutoload.js
    - Kernel/Dispatcher/DispatcherMaster.js
    - Kernel/Dispatcher/DispatcherBase.js
    - Kernel/Factory/MasterFactory.js
    - Kernel/Initializer/MasterInitializer.js
    - Kernel/Initializer/ModuleInitializer.js
    - Kernel/Managers/MasterManager.js
    - Kernel/Managers/RouteManager.js
    - Kernel/Managers/ServiceManager.js
    - Kernel/Managers/ModelManager.js
    - Kernel/Managers/TemplateManager.js
    - Kernel/Managers/ControllerManager.js
    - Kernel/Managers/EntityManager.js
    - Kernel/Managers/CollectionManager.js
    - Kernel/Route/MasterRoute.js
    - Kernel/Service/MasterService.js
    - Kernel/Route/Type/MasterRouteType.js
    - Kernel/Route/Type/LitteralRouteType.js
    - Kernel/Route/Type/TranslationRouteType.js
    - Kernel/Route/Type/ParamsRouteType.js
    - Kernel/Controller/MasterController.js
    - Kernel/Collection/MasterCollection.js
    - Kernel/Entity/MasterEntity.js
    - Kernel/Template/MasterTemplate.js
    - Kernel/Template/View/MasterView.js
    - Kernel/Template/ContentTemplate.js
    - Kernel/Template/View/ContentView.js
    - Modules/Example/ExampleAutoload.js
    - Modules/Body/BodyAutoload.js
    - Modules/Client/ClientAutoload.js
    - Modules/Navigation/NavigationAutoload.js
    - Modules/User/UserAutoload.js
    - Modules/Timeline/TimelineAutoload.js
    - Modules/Notification/NotificationAutoload.js
    - Modules/Panel/PanelAutoload.js
    - Modules/Store/StoreAutoload.js
    - Modules/Element/ElementAutoload.js
    - Modules/Data/DataAutoload.js
    - Modules/NamedData/NamedDataAutoload.js
    - Modules/BaseUser/BaseUserAutoload.js
    - Modules/Student/StudentAutoload.js
    - Modules/Institute/InstituteAutoload.js
    - Modules/Company/CompanyAutoload.js
    - Modules/School/SchoolAutoload.js
    - Modules/Example/Bundle/Book/Route/ExampleBookMainRoute.js
    - Modules/Example/Bundle/Book/Service/ExampleBookMainService.js
    - Modules/Example/Bundle/Author/Route/ExampleAuthorMainRoute.js
    - Modules/Example/Bundle/Author/Service/ExampleAuthorMainService.js
    - Modules/Example/Bundle/Book/Service/Factory/ExampleBookServiceMainFactory.js
    - Modules/Example/Bundle/Book/Controller/ExampleBookMainController.js
    - Modules/Example/Bundle/Author/Template/ExampleAuthorMainTemplate.js
    - Modules/Example/Bundle/Author/Template/View/ExampleAuthorTemplateMainView.js
    - Modules/Example/Bundle/Book/Template/ExampleBookMainTemplate.js
    - Modules/Example/Bundle/Book/Template/View/ExampleBookTemplateMainView.js
    - Modules/Body/Bundle/Right/Template/BodyRightMainTemplate.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateMainView.js
    - Modules/Body/Bundle/Right/Template/BodyRightHeaderTemplate.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateHeaderView.js
    - Modules/Body/Bundle/Left/Template/BodyLeftMainTemplate.js
    - Modules/Body/Bundle/Left/Template/View/BodyLeftTemplateMainView.js
    - Modules/Body/Bundle/Left/Template/View/BodyLeftTemplateLogoView.js
    - Modules/Body/Bundle/Left/Template/BodyLeftLogoTemplate.js
    - Modules/Body/Bundle/Cover/Template/BodyCoverMainTemplate.js
    - Modules/Body/Bundle/Cover/Template/View/BodyCoverTemplateMainView.js
    - Modules/Client/Bundle/Websocket/Service/ClientWebsocketMainService.js
    - Modules/Client/Bundle/Auth/Service/ClientAuthMainService.js
    - Modules/Body/Bundle/Right/Template/BodyRightHeaderTemplate.js
    - Modules/Notification/Bundle/Panel/Template/NotificationPanelMainTemplate.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateHeaderView.js
    - Modules/Notification/Bundle/Panel/Template/View/NotificationPanelTemplateMainView.js
    - Modules/Navigation/Bundle/Action/Service/NavigationActionLinkService.js
    - Modules/Navigation/Bundle/History/Service/NavigationHistoryMainService.js
    - Modules/Navigation/Bundle/Title/Service/NavigationTitleChangeService.js
    - Modules/Body/Bundle/Base/Template/BodyBaseMainView.js
    - Modules/Body/Bundle/Base/Template/View/BodyBaseTemplateMainView.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateBreadcrumView.js
    - Modules/Body/Bundle/Right/Template/BodyRightViewBreadcrum.js
    - Modules/Navigation/Bundle/Resize/Service/NavigationResizeManageService.js
    - Modules/Panel/Bundle/Filter/Service/PanelFilterMainService.js
    - Modules/Panel/Bundle/Filter/Template/PanelFilterAbstractTemplate.js
    - Modules/Panel/Bundle/Filter/Template/PanelFilterMainTemplate.js
    - Modules/Panel/Bundle/Filter/Template/PanelFilterActionTemplate.js
    - Modules/Panel/Bundle/Filter/Template/View/PanelFilterTemplateAbstractView.js
    - Modules/Panel/Bundle/Filter/Template/View/PanelFilterTemplateMainView.js
    - Modules/Panel/Bundle/Filter/Template/View/PanelFilterTemplateActionView.js
    - Modules/Store/Bundle/Manager/Service/StoreManagerMainService.js
    - Modules/Example/Bundle/Author/Collection/ExampleAuthorMainCollection.js
    - Modules/Example/Bundle/Book/Collection/ExampleBookMainCollection.js
    - Modules/Element/Bundle/Data/Collection/ElementDataMainCollection.js
    - Modules/Element/Bundle/Data/Entity/ElementDataMainEntity.js
    - Modules/Element/Bundle/Data/Route/ElementDataMainRoute.js
    - Modules/Element/Bundle/Data/Template/ElementDataTimelineTemplate.js
    - Modules/Element/Bundle/Data/Template/View/ElementDataTemplateTimelineView.js
    - Modules/Element/Bundle/Data/Template/View/ElementDataTemplateMiniatureView.js
    - Modules/Element/Bundle/Data/Template/ElementDataMiniatureTemplate.js
    - Modules/Data/Bundle/Data/Collection/DataDataMainCollection.js
    - Modules/Data/Bundle/Data/Entity/DataDataMainEntity.js
    - Modules/Data/Bundle/Data/Route/DataDataMainRoute.js
    - Modules/Data/Bundle/Data/Template/DataDataTimelineTemplate.js
    - Modules/Data/Bundle/Data/Template/View/DataDataTemplateTimelineView.js
    - Modules/Data/Bundle/Data/Template/DataDataMiniatureTemplate.js
    - Modules/Data/Bundle/Data/Template/View/DataDataTemplateMiniatureView.js
    - Modules/BaseUser/Bundle/Data/Collection/BaseUserDataMainCollection.js
    - Modules/BaseUser/Bundle/Data/Entity/BaseUserDataMainEntity.js
    - Modules/BaseUser/Bundle/Data/Route/BaseUserDataMainRoute.js
    - Modules/BaseUser/Bundle/Data/Template/BaseUserDataTimelineTemplate.js
    - Modules/BaseUser/Bundle/Data/Template/View/BaseUserDataTemplateTimelineView.js
    - Modules/BaseUser/Bundle/Data/Template/BaseUserDataMiniatureTemplate.js
    - Modules/BaseUser/Bundle/Data/Template/View/BaseUserDataTemplateMiniatureView.js
    - Modules/Student/Bundle/Data/Collection/StudentDataMainCollection.js
    - Modules/Student/Bundle/Display/Service/StudentDisplayMainService.js
    - Modules/Student/Bundle/Display/Template/StudentDisplayMainTemplate.js
    - Modules/Student/Bundle/Display/Template/View/StudentDisplayTemplateMainView.js
    - Modules/Student/Bundle/Data/Route/StudentDataMainRoute.js
    - Modules/Student/Bundle/Data/Entity/StudentDataMainEntity.js
    - Modules/Student/Bundle/Data/Template/StudentDataTimelineTemplate.js
    - Modules/Student/Bundle/Data/Template/View/StudentDataTemplateTimelineView.js
    - Modules/NamedData/Bundle/Data/Collection/NamedDataDataMainCollection.js
    - Modules/NamedData/Bundle/Data/Entity/NamedDataDataMainEntity.js
    - Modules/NamedData/Bundle/Data/Route/NamedDataDataMainRoute.js
    - Modules/NamedData/Bundle/Data/Template/NamedDataDataTimelineTemplate.js
    - Modules/NamedData/Bundle/Data/Template/View/NamedDataDataTemplateTimelineView.js
    - Modules/Institute/Bundle/Data/Entity/InstituteDataMainEntity.js
    - Modules/Institute/Bundle/Data/Collection/InstituteDataMainCollection.js
    - Modules/Institute/Bundle/Data/Route/InstituteDataMainRoute.js
    - Modules/Institute/Bundle/Data/Template/InstituteDataTimelineTemplate.js
    - Modules/Institute/Bundle/Data/Template/View/InstituteDataTemplateTimelineView.js
    - Modules/School/Bundle/Data/Collection/SchoolDataMainCollection.js
    - Modules/School/Bundle/Data/Entity/SchoolDataMainEntity.js
    - Modules/School/Bundle/Data/Route/SchoolDataMainRoute.js
    - Modules/School/Bundle/Data/Template/SchoolDataTimelineTemplate.js
    - Modules/School/Bundle/Data/Template/View/SchoolDataTemplateTimelineView.js
    - Modules/Company/Bundle/Data/Collection/CompanyDataMainCollection.js
    - Modules/Company/Bundle/Data/Entity/CompanyDataMainEntity.js
    - Modules/Company/Bundle/Data/Route/CompanyDataMainRoute.js
    - Modules/Company/Bundle/Data/Template/View/CompanyDataTemplateTimelineView.js
    - Modules/Company/Bundle/Data/Template/CompanyDataTimelineTemplate.js
    - Modules/Navigation/Bundle/Cookie/Service/NavigationCookieMainService.js
    - Modules/Navigation/Bundle/Route/NavigationRouteMainService.js
    - Modules/User/Bundle/Manager/Service/UserManagerMainService.js
    - Modules/Navigation/Bundle/Loader/Template/NavigationLoaderMainTemplate.js
    - Modules/Navigation/Bundle/Loader/Template/View/NavigationLoaderTemplateMainView.js
    - Modules/Navigation/Bundle/Loader/Service/NavigationLoaderMainService.js
    - main.js
styles : 
    - Assets/css/all.css
