scripts:
    - Kernel/Config.js
    - Kernel/Router.js
    - Kernel/Utility.js
    - Kernel/ServiceLocator.js
    - Kernel/Translator.js
    - Kernel/Autoload/MasterAutoload.js
    - Kernel/Dispatcher/DispatcherMaster.js
    - Kernel/Dispatcher/DispatcherBase.js
    - Kernel/Factory/MasterFactory.js
    - Kernel/Initializer/MasterInitializer.js
    - Kernel/Initializer/ModuleInitializer.js
    - Kernel/Managers/MasterManager.js
    - Kernel/Managers/RouteManager.js
    - Kernel/Managers/ServiceManager.js
    - Kernel/Route/MasterRoute.js
    - Kernel/Service/MasterService.js
    - Modules/Example/ExampleAutoload.js
    - Kernel/Route/Type/MasterRouteType.js
    - Kernel/Route/Type/LitteralRouteType.js
    - Kernel/Route/Type/TranslationRouteType.js
    - Kernel/Route/Type/ParamsRouteType.js
    - Modules/Example/Route/BookRoute.js
    - Modules/Example/Route/AuthorRoute.js
    - Modules/Example/Service/BookService.js
    - Modules/Example/Service/AuthorService.js
    - Modules/Example/Service/Factory/BookServiceFactory.js
    - main.js