scripts : 
    - Vendors/React.js
    - Vendors/socket.io.js
    - Kernel/Config.js
    - Kernel/Router.js
    - Kernel/Utility.js
    - Kernel/ServiceLocator.js
    - Kernel/Translation.js
    - Kernel/Translator.js
    - Kernel/Autoload/MasterAutoload.js
    - Kernel/Dispatcher/DispatcherMaster.js
    - Kernel/Dispatcher/DispatcherBase.js
    - Kernel/Factory/MasterFactory.js
    - Kernel/Initializer/MasterInitializer.js
    - Kernel/Initializer/ModuleInitializer.js
    - Kernel/Managers/MasterManager.js
    - Kernel/Managers/RouteManager.js
    - Kernel/Managers/ServiceManager.js
    - Kernel/Managers/ModelManager.js
    - Kernel/Managers/TemplateManager.js
    - Kernel/Managers/ControllerManager.js
    - Kernel/Managers/EntityManager.js
    - Kernel/Route/MasterRoute.js
    - Kernel/Service/MasterService.js
    - Kernel/Route/Type/MasterRouteType.js
    - Kernel/Route/Type/LitteralRouteType.js
    - Kernel/Route/Type/TranslationRouteType.js
    - Kernel/Route/Type/ParamsRouteType.js
    - Kernel/Controller/MasterController.js
    - Kernel/Template/MasterTemplate.js
    - Kernel/Template/View/MasterView.js
    - Modules/Example/ExampleAutoload.js
    - Modules/Example/Bundle/Book/Route/ExampleBookMainRoute.js
    - Modules/Example/Bundle/Book/Service/ExampleBookMainService.js
    - Modules/Example/Bundle/Author/Route/ExampleAuthorMainRoute.js
    - Modules/Example/Bundle/Author/Service/ExampleAuthorMainService.js
    - Modules/Example/Bundle/Book/Service/Factory/ExampleBookServiceMainFactory.js
    - Modules/Example/Bundle/Book/Controller/ExampleBookMainController.js
    - Modules/Example/Bundle/Author/Template/ExampleAuthorMainTemplate.js
    - Modules/Example/Bundle/Author/Template/View/ExampleAuthorTemplateMainView.js
    - Modules/Example/Bundle/Book/Template/ExampleBookMainTemplate.js
    - Modules/Example/Bundle/Book/Template/View/ExampleBookTemplateMainView.js
    - Modules/Body/BodyAutoload.js
    - Modules/Body/Bundle/Right/Template/BodyRightMainTemplate.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateMainView.js
    - Modules/Body/Bundle/Right/Template/BodyRightHeaderTemplate.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateHeaderView.js
    - Modules/Body/Bundle/Left/Template/BodyLeftMainTemplate.js
    - Modules/Body/Bundle/Left/Template/View/BodyLeftTemplateMainView.js
    - Modules/Body/Bundle/Left/Template/View/BodyLeftTemplateLogoView.js
    - Modules/Body/Bundle/Left/Template/BodyLeftLogoTemplate.js
    - Modules/Body/Bundle/Cover/Template/BodyCoverMainTemplate.js
    - Modules/Body/Bundle/Cover/Template/View/BodyCoverTemplateMainView.js
    - Modules/Client/ClientAutoload.js
    - Modules/Client/Bundle/Websocket/Service/ClientWebsocketMainService.js
    - Modules/Client/Bundle/Auth/Service/ClientAuthMainService.js
    - Modules/Navigation/NavigationAutoload.js
    - Modules/Notification/NotificationAutoload.js
    - Modules/User/UserAutoload.js
    - Modules/Body/Bundle/Right/Template/BodyRightHeaderTemplate.js
    - Modules/Notification/Bundle/Panel/Template/NotificationPanelMainTemplate.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateHeaderView.js
    - Modules/Notification/Bundle/Panel/Template/View/NotificationPanelTemplateMainView.js
    - Modules/Navigation/Bundle/Action/Service/NavigationActionLinkService.js
    - Modules/Store/StoreAutoload.js
    - Modules/Navigation/Bundle/History/Service/NavigationHistoryMainService.js
    - Modules/Navigation/Bundle/Title/Service/NavigationTitleChangeService.js
    - Modules/Body/Bundle/Base/Template/BodyBaseMainView.js
    - Modules/Body/Bundle/Base/Template/View/BodyBaseTemplateMainView.js
    - Modules/Body/Bundle/Right/Template/View/BodyRightTemplateBreadcrumView.js
    - Modules/Body/Bundle/Right/Template/BodyRightViewBreadcrum.js
    - Modules/Timeline/TimelineAutoload.js
    - Modules/Navigation/Bundle/Resize/Service/NavigationResizeManageService.js
    - Modules/Panel/PanelAutoload.js
    - Modules/Panel/Bundle/Filter/Service/PanelFilterMainService.js
    - Modules/Panel/Bundle/Filter/Template/PanelFilterAbstractTemplate.js
    - Modules/Panel/Bundle/Filter/Template/PanelFilterMainTemplate.js
    - Modules/Panel/Bundle/Filter/Template/PanelFilterActionTemplate.js
    - Modules/Panel/Bundle/Filter/Template/View/PanelFilterTemplateAbstractView.js
    - Modules/Panel/Bundle/Filter/Template/View/PanelFilterTemplateMainView.js
    - Modules/Panel/Bundle/Filter/Template/View/PanelFilterTemplateActionView.js
    - main.js
styles : 
    - Assets/css/all.css