###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-06-24 16:55:48
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-10-16 15:11:46
###############################################################

Example: true
Body: true
Client: true
Notification: true
Navigation: true
Store: true
Panel: true
Student: true
Element: true
Data: true
User: true
BaseUser: true
NamedData: true
Institute: true
Company: true
School: true
Filter: true
Skill: true
Link: true
SkillLink: true
Project : true
BaseUserCompany: true