Example: true
Body: true
Client: true
Notification: true
Navigation: true
Store: true
Panel: true
Student: true
Element: true
Data: true
User : true
BaseUser: true
NamedData: true
Institute: true
Company: true
School: true
