###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-06-24 16:55:48
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-11-05 23:28:37
###############################################################

element_data_main_route:
institute_data_main_route:
student_data_main_route:
	studentfilter_data_main_route:
		skilllink_data_main_route:
		challengelink_data_main_route:
company_data_main_route:
	companyfilter_data_main_route:
		skilllink_data_main_route:
		eligibility_data_main_route:
	agent_data_main_route:
	recruiter_data_main_route:
	baseusercompany_data_main_route:
school_data_main_route:
filter_data_main_route:
skill_data_main_route:
link_data_main_route:
	skilllink_data_main_route:
skilllink_data_main_route:
baseusercompany_data_main_route:
agent_data_main_route:
recruiter_data_main_route:
studentfilter_data_main_route:
companyfilter_data_main_route:
challenge_data_main_route:
challengelink_data_main_route:
eligibility_data_main_route:
