###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-06-24 16:55:48
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-10-16 16:30:04
###############################################################

element_data_main_route:
student_data_main_route:
	filter_data_main_route:
		skilllink_data_main_route:
company_data_main_route:
	filter_data_main_route:
		skilllink_data_main_route:
school_data_main_route:
filter_data_main_route:
skill_data_main_route:
link_data_main_route:
	skilllink_data_main_route:
skilllink_data_main_route:
baseusercompany_data_main_route: