invokables:
    Translation : Kernel/Translation
    Translator : Kernel/Translator
    RouteManager : Kernel/Managers/RouteManager
    ServiceManager : Kernel/Managers/ServiceManager
    TemplateManager : Kernel/Managers/TemplateManager
    ControllerManager : Kernel/Managers/ControllerManager
    EntityManager : Kernel/Managers/EntityManager
    Router : Kernel/Router
    Dispatcher : Kernel/Dispatcher/DispatcherBase

    ModuleInitializer : Kernel/Initializer/ModuleInitializer
shared:
    Translator : false
