###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-06-06 06:42:18
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-09-20 00:22:10
###############################################################

invokables:
    Translation : Kernel/Translation
    Translator : Kernel/Translator
    RouteManager : Kernel/Managers/RouteManager
    ServiceManager : Kernel/Managers/ServiceManager
    TemplateManager : Kernel/Managers/TemplateManager
    ControllerManager : Kernel/Managers/ControllerManager
    CollectionManager : Kernel/Managers/CollectionManager
    EntityManager : Kernel/Managers/EntityManager
    FormManager : Kernel/Managers/FormManager
    HelperManager : Kernel/Managers/HelperManager
    FormElementManager : Kernel/Managers/FormElementManager
    FilterManager : Kernel/Managers/FilterManager
    ValidatorManager : Kernel/Managers/ValidatorManager
    Router : Kernel/Router
    Dispatcher : Kernel/Dispatcher/DispatcherBase
    ModuleInitializer : Kernel/Initializer/ModuleInitializer
shared:
    Translator : true
    Translation : true
